### ISSUE TITLE
Suggested Improvement | Subtle animations

### ISSUE THREAD

**Issue by sam08sk** [lotos-linux/hypr-dock#2]
I like the gnome Dash to Dock Animated extension and tried to add a little movement to the dock icons:
1. ~/.config/hypr-dock/themes/lotos/style.css

```css
/* Dock window background: transparent + blur handled by Hyprland */
window {
  background-color: rgba(20, 20, 20, 0.25);  /* slight tint for blur visibility */
  border-radius: 20px;
  padding: 8px;
}

/* App container */
#app {
  background: transparent;
  border-radius: 16px;
  margin: 6px;
}

/* App buttons: basic look */
button {
  background-color: transparent;
  padding: 10px 10px 8px 10px;
  border-radius: 16px;
  border: none;
  transition: background-color 0.2s ease-in-out, box-shadow 0.2s ease-in-out, padding 0.2s ease-in-out, margin 0.2s ease-in-out;
}

/* Hover: highlight with enhanced raise effect and glow, minimal disturbance */
button:hover {
  box-shadow: 0 5px 8px rgba(255, 255, 255, 0.2), 0 2px 3px rgba(255, 255, 255, 0.1); /* Stronger vertical offset for elevation */
  background-color: rgba(255, 255, 255, 0.06);
  padding: 14px 10px 6px 10px; /* Increase top padding more, decrease bottom for noticeable lift */
  margin: -4px 0 2px 0; /* Stronger upward shift, slight bottom margin to balance */
  border-radius: 16px;
}

/* App icons: fixed size with lift on hover */
button image {
  border-radius: 8px;
  margin: 0;
  min-width: 32px;
  min-height: 32px;
  transition: margin 0.25s ease-in-out; /* Smooth transition for icon lift */
}

/* Lift the icon itself on button hover */
button:hover image {
  margin: -4px 0 0 0; /* Pull the icon up by 4px to match button lift */
}

#app.active {
  background-color: rgba(255, 255, 255, 0.08);
  border-radius: 16px;
}
```

2. ~/.config/hypr-dock/themes/lotos/lotos.jsonc
```json
{
    "Blur": "true",
    "Spacing": 6
}
```
3. ~/.config/hypr-dock/config.jsonc
```json
{
    "CurrentTheme": "lotos",
    "IconSize": 36,
    "Layer": "auto",
    "Position": "bottom",
    "SystemGapUsed": "true",
    "Margin": 8
}
```

Cheers
Sam

![Image](https://github.com/user-attachments/assets/d82b5eb9-fd90-4db1-9c4e-ebb51282d0c5)

```

**Comment by sujer-ux** [comment]
Hi Sam!  

Thanks for your contribution to the project. Cool theme!  

But there's a nuance (my bad, as I forgot to mention it in the docs):  
In **hypr-dock**, the panel's appearance (rounding, background) should be configured not via `window` in CSS, but through the `#app` container.  
This is due to the logic handling the dock's offset from the screen edge.  
The `window` itself is invisible, and the only thing you need to set for it is `background-color: transparent`.  

Check out this screenshot: 
![Image](https://github.com/user-attachments/assets/db1e3299-1f4d-42db-8e79-8c12c4093044)

The margin is dynamically set in the code based on either `general:gaps_out` or the `Margin` line in the config (depending on the `SystemGapUsed` parameter).  
So, with your current theme, the dynamic margin would break the panel's appearance.  
I recommend styling the panel via `#app`:  

```css
window {
  background-color: transparent;
}

#app {
  background-color: rgba(20, 20, 20, 0.25);
  border-radius: 20px;
  padding: 8px;
  margin: 6px;
}

...
```

If you'd like, I can add your animations as a separate theme in the repo.
Adjust the CSS and create a Pull Request with your theme (e.g., `themes/sam08sk/...`).
